require File.dirname(__FILE__) + '/AutomatedBatch.rb'
require File.dirname(__FILE__) + '/AutomatedBatchMappingRegistry.rb'
require 'soap/rpc/driver'

module Postini::API::AutomatedBatch #:nodoc: all

class AutomatedBatchPort < ::SOAP::RPC::Driver
  Methods = [
    [ "",
      "test",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "test"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "testResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::StatusException"=>{:use=>"literal", :namespace=>nil, :name=>"StatusException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "checkauth",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "checkauth"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "checkauthResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "addalias",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "addalias"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "addaliasResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "adddomain",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "adddomain"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "adddomainResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "addorg",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "addorg"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "addorgResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "adduser",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "adduser"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "adduserResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "deletealias",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deletealias"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deletealiasResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "deletedomain",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deletedomain"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deletedomainResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "deleteorg",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deleteorg"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deleteorgResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "deleteuser",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deleteuser"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "deleteuserResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "displaydomain",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displaydomain"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displaydomainResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "displayorg",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displayorg"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displayorgResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "displayspool",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displayspool"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displayspoolResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "displayuser",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displayuser"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "displayuserResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "getorgreport",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "getorgreport"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "getorgreportResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "listdomains",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "listdomains"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "listdomainsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "listorgs",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "listorgs"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "listorgsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "listusers",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "listusers"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "listusersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "modifydomain",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "modifydomain"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "modifydomainResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "modifyorg",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "modifyorg"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "modifyorgResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "modifyuser",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "modifyuser"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "modifyuserResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ],
    [ "",
      "suspenduser",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "suspenduser"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "http://postini.com/PSTN/SOAPAPI/v2/automatedbatch", "suspenduserResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"Postini::API::AutomatedBatch::AuthenticationException"=>{:use=>"literal", :namespace=>nil, :name=>"AuthenticationException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InvalidValueException"=>{:use=>"literal", :namespace=>nil, :name=>"InvalidValueException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::NoSuchKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"NoSuchKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::BatchException"=>{:use=>"literal", :namespace=>nil, :name=>"BatchException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MissingElementException"=>{:use=>"literal", :namespace=>nil, :name=>"MissingElementException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::InternalException"=>{:use=>"literal", :namespace=>nil, :name=>"InternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::UnknownInternalException"=>{:use=>"literal", :namespace=>nil, :name=>"UnknownInternalException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::AdminBlockException"=>{:use=>"literal", :namespace=>nil, :name=>"AdminBlockException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}, "Postini::API::AutomatedBatch::MalformedKeyException"=>{:use=>"literal", :namespace=>nil, :name=>"MalformedKeyException", :encodingstyle=>"document", :ns=>"http://postini.com/PSTN/SOAPAPI/v2/automatedbatch"}} }
    ]
  ]

  def initialize(endpoint_url)
    super(endpoint_url, nil)
    self.mapping_registry = AutomatedBatchMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = AutomatedBatchMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end


end
