# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: postini 0.2.0pre ruby lib

Gem::Specification.new do |s|
  s.name = "postini"
  s.version = "0.2.0pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["kenneth.kalmer@gmail.com"]
  s.date = "2014-02-21"
  s.description = "Library to make the Postini SOAP API more palatable"
  s.email = "kenneth.kalmer@gmail.com"
  s.extra_rdoc_files = [
    "History.txt",
    "License.txt",
    "PostInstall.txt",
    "README.txt",
    "TODO"
  ]
  s.files = [
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "License.txt",
    "PostInstall.txt",
    "README.txt",
    "Rakefile",
    "TODO",
    "config/website.yml",
    "lib/postini.rb",
    "lib/postini/automated_batch_service.rb",
    "lib/postini/configuration_check.rb",
    "lib/postini/endpoint_resolver_service.rb",
    "lib/postini/endpoints.rb",
    "lib/postini/exceptions.rb",
    "postini.gemspec",
    "script/console",
    "script/destroy",
    "script/generate",
    "script/txt2html",
    "spec/exceptions_spec.rb",
    "spec/postini_spec.rb",
    "spec/rcov.opts",
    "spec/spec_helper.rb",
    "tasks/rspec.rake",
    "vendor/automatedbatch.wsdl",
    "vendor/endpointresolver.wsdl",
    "website/index.txt",
    "website/javascripts/rounded_corners_lite.inc.js",
    "website/spam_box.png",
    "website/stylesheets/screen.css",
    "website/template.html.erb"
  ]
  s.homepage = "http://postini4r.rubyforge.org"
  s.post_install_message = "\nFor more information on postini4r's postini gem, see \nhttp://postini4r.rubyforge.org/postini\n\nRemember to contact your Postini provider, or Postini directly, to gain access\nto the Postini Early Access Program. You'll need a unique API key to make use\nof this gem.\n\n"
  s.rubygems_version = "2.2.2"
  s.summary = "Library to make the Postini SOAP API more palatable"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<handsoap>, [">= 0"])
      s.add_runtime_dependency(%q<curb>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.5.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.1"])
    else
      s.add_dependency(%q<handsoap>, [">= 0"])
      s.add_dependency(%q<curb>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.14.0"])
      s.add_dependency(%q<bundler>, ["~> 1.5.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
    end
  else
    s.add_dependency(%q<handsoap>, [">= 0"])
    s.add_dependency(%q<curb>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.14.0"])
    s.add_dependency(%q<bundler>, ["~> 1.5.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.1"])
  end
end

