# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{postini}
  s.version = "0.2.0pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["kenneth.kalmer@gmail.com"]
  s.date = %q{2010-07-14}
  s.description = %q{Library to make the Postini SOAP API more palatable}
  s.email = %q{kenneth.kalmer@gmail.com}
  s.extra_rdoc_files = [
    "History.txt",
     "License.txt",
     "PostInstall.txt",
     "README.txt",
     "TODO"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "License.txt",
     "PostInstall.txt",
     "README.txt",
     "Rakefile",
     "TODO",
     "config/website.yml",
     "features/development.feature",
     "features/step_definitions/common_steps.rb",
     "features/support/common.rb",
     "features/support/env.rb",
     "features/support/matchers.rb",
     "lib/postini.rb",
     "lib/postini/automated_batch_service.rb",
     "lib/postini/configuration_check.rb",
     "lib/postini/endpoint_resolver_service.rb",
     "lib/postini/endpoints.rb",
     "lib/postini/exceptions.rb",
     "postini4r-postini.gemspec",
     "script/console",
     "script/destroy",
     "script/generate",
     "script/txt2html",
     "spec/exceptions_spec.rb",
     "spec/postini_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake",
     "vendor/automatedbatch.wsdl",
     "vendor/endpointresolver.wsdl",
     "website/index.txt",
     "website/javascripts/rounded_corners_lite.inc.js",
     "website/spam_box.png",
     "website/stylesheets/screen.css",
     "website/template.html.erb"
  ]
  s.homepage = %q{http://postini4r.rubyforge.org}
  s.post_install_message = %q{
For more information on postini4r's postini gem, see 
http://postini4r.rubyforge.org/postini

Remember to contact your Postini provider, or Postini directly, to gain access
to the Postini Early Access Program. You'll need a unique API key to make use
of this gem.

}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Library to make the Postini SOAP API more palatable}
  s.test_files = [
    "spec/exceptions_spec.rb",
     "spec/postini_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<handsoap>, [">= 0"])
      s.add_runtime_dependency(%q<curb>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<handsoap>, [">= 0"])
      s.add_dependency(%q<curb>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<handsoap>, [">= 0"])
    s.add_dependency(%q<curb>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end

